using System.Text.RegularExpressions;
using UnityEditor;
using System.IO;
using System.Text;
using System.Linq;

namespace MicheliniDev.Utils.EventBus.Editor
{
    public class EventBusGenerator : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool eventsModified = importedAssets.Any(path =>
                AssetDatabase.GetMainAssetTypeAtPath(path) == typeof(GlobalBusEvents));

            if (eventsModified)
                EditorApplication.delayCall += RegenerateEventConstants;
        }

        private static void RegenerateEventConstants()
        {
            var guids = AssetDatabase.FindAssets("t:GlobalBusEvents");

            if (guids.Length == 0) return;

            string path = AssetDatabase.GUIDToAssetPath(guids[0]);
            GlobalBusEvents eventsSO = AssetDatabase.LoadAssetAtPath<GlobalBusEvents>(path);

            if (eventsSO == null) return;

            GenerateClass(eventsSO, path);
        }

        private static void GenerateClass(GlobalBusEvents script, string assetPath)
        {
            string className = "EventConstants";
            string folderPath = Path.GetDirectoryName(assetPath);
            string filePath = Path.Combine(folderPath, className + ".cs");

            StringBuilder sb = new StringBuilder();

            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("");
            sb.AppendLine("namespace MicheliniDev.Utils.EventBus");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated by EventBusGenerator. Do not modify manually.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            foreach (var eventName in script.EventNames)
            {
                if (string.IsNullOrWhiteSpace(eventName)) continue;

                string validName = MakeValidIdentifier(eventName);

                sb.AppendLine($"        public static readonly int {validName} = Animator.StringToHash(\"{eventName}\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();
        }

        private static string MakeValidIdentifier(string input)
        {
            string baseReplace = Regex.Replace(input, @"\s+", "_");
            string clean = Regex.Replace(baseReplace, @"[^\w]", "");

            if (char.IsDigit(clean[0]))
                clean = "_" + clean;

            return clean;
        }
    }
}